version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - '3306:3306'
